spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: