spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true